export const CHANGE_SEARCH = 'CHANGE_SEARCH';

export const FETCH_CHARS_PENDING = 'FETCH_CHARS_PENDING';
export const FETCH_CHARS_SUCCESS = 'FETCH_CHARS_SUCCESS';
export const FETCH_CHARS_FAIL = 'FETCH_CHARS_FAIL';